### PR TITLE
Implemented user registration.

### PR DESCRIPTION
**Pull request by sush-mit**

### CODE REVIEW

**Comment by sush-mit** [comment]
image
image

**Comment by mi5t4n** [comment]
Add first name and last name field to registration page .

**Comment by sush-mit** [comment]
Added first name and last name fields to registration page.
image

**Comment by mi5t4n** [comment]
It seems you haven't use the pipenv to virtualize the project. So, it is hard for me to initialize the project. Please, use pipenv or some virtualization.

**Comment by sush-mit** [comment]
> It seems you haven't use the pipenv to virtualize the project.

I have used pipenv. Do I include the pipfiles too?

**Pull request merged**
